ALTER TABLE persons ADD COLUMN IF NOT EXISTS tier2_contact_field VARCHAR(10) NOT NULL DEFAULT 'phone';
ALTER TABLE persons ADD COLUMN IF NOT EXISTS confirmed_members_only BOOLEAN NOT NULL DEFAULT FALSE;
